# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
nfpms:
  - id: packages # here we say that artifacts built with nfpm will be identified with `packages` string.
    maintainer: Dominik Schidlowski (Sauron) <dominik@schidlowski.eu>
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
    dependencies:
      - libnetfilter-log1
    contents:
      - src: configs/nftables-exporter.service
        dst: /lib/systemd/system/nftables-exporter.service
        file_info:
          mode: 0640
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
    deb:
      signature:
        key_file: /signature/deb.gpg
release:
  disable: true
publishers:
  - name: my-publisher
    cmd: 'curl -u "admin:{{ .Env.NEXUS_PASSWORD }}" -H "Content-Type: multipart/form-data" --data-binary "@{{ abs .ArtifactPath }}" "{{ .Env.NEXUS_REPOSITORY }}"'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
